config/routes.rb
Questionnaire::Application.routes.draw do

  resources :forms

end

app/models/form.rb
class Form < ActiveRecord::Base
  attr_accessible :email, :name, :company, :job_title, :comment, :rating, :would_recommend

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true

  validates :rating, presence: true, numericality: {
  	greater_than_or_equal_to: 1, 
  	less_than_or_equal_to: 5,
  	only_interger: true
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def index
  	# This is a comment
  	@name = "Dan"
  	@location ="Steer"
  	@now = Time.now
  	# @message = "Welcome to " + @location + ", " + @name
  	@message = "Welcome to #{@location}, #{@name}"

		# This is an array
   @list = ["Rik", "Amelia", "Tim", "Calum"]

   @competition_won_by_sev = true

   @sev_votes = rand(100)
   @mark_votes = rand(100)

   if @sev_votes > @mark_votes
    @list << "Sev"
  elsif @sev_votes == @mark_votes
    @list << "Sev"
    @list << "Mark"
  else
    @list << "Mark"
  end

  @forms = Form.order("rating")

  end

  def show
   @form = Form.find(params[:id])
  end

  def new
   @form = Form.new
  end

  def create
   @form = Form.new(params[:form])
     if @form.save
      flash[:success] = "You have sucessfully added a reponse!"
      redirect_to forms_path
    else
      render "new"
    end
  end

  def edit
    @form = Form.find params[:id]
  end 

  def update
    @form = Form.find params[:id]
    if @form.update_attributes(params[:form])
      flash[:success] = "You have sucessfully edited #{@form.name}!"
      redirect_to form_path(@form)
    else
      render "edit"
    end
  end

  def destroy
    @form = Form.find params[:id]
    @form.destroy
      if @form.destroy
      flash[:success] = "You have sucessfully deleted the #{@form.name}!"
      end
    redirect_to forms_path
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= simple_form_for @form do |f| %>
  <%= f.input :name, label: "Full name" %>
  <%= f.input :email, label: "E-Mail address", placeholder: 'user@domain.com' %>
  <%= f.input :job_title, label: "Job Title" %>
  <%= f.input :company, label: "Company Name" %>
  <%= f.input :comment, class: "input-xlarge" %>
  <%= f.input :rating, as: :select, collection: [1,2,3,4,5] %>
  <%= f.input :would_recommend %>
  <%= f.button :submit, class: "btn btn-small btn-success" %>
<% end %>

app/views/forms/edit.html.erb
<h1>Edit form</h1>

<%= render partial: "form", locals: { btn: "Update response"} %>

app/views/forms/index.html.erb
<h1>Form Responses</h1>

<!--p><%= "my name is dan".titleize.gsub("a", "4").split (" ") %></p-->

<!-- <p><%= @name %></p>
<p><%= @location %></p>
<p><%= @now %></p>
<p><%= @message %></p>

<h2>Steer is <%= @list.size %> people:</h2>

<h2>Competition</h2>

<ul>
	<li>Sev got <%= @sev_votes %> votes </li>
	<li>Mark got <%= @mark_votes %> votes </li>	
</ul>

<ul>
	<% @list.each do |person| %>
	<li>Person: <%= person %></li>
	<% end %>
</ul> -->

<div class="row-fluid">
  <div class="span12">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>E-Mail</th>
          <th>Job title</th>
          <th>Rating</th>
          <th>Recommended?</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
      <% @forms.each do |form| %>
        <tr>
          <td><%= link_to form.name, form_path(form) %></td>
          <td><%= form.email %></td>
          <td><%= form.job_title %></td>
          <td><%= form.rating %></td>
          <td><%= form.would_recommend %></td>
          <td><%= link_to "Edit", edit_form_path(form), class: "btn btn-success btn-mini" %></td>
          <td><%= link_to "Delete", form_path(form), method: :delete, confirm: "Are you sure?", class: "btn btn-danger btn-mini" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/new.html.erb
<h1>New form</h1>

<%= render partial: "form", locals: { btn: "Add response"} %>

app/views/forms/show.html.erb
<h1>User name:<%= @form.name %></h1>
<p><strong>E-Mail:</strong> <%= @form.email %></p>
<p><strong>Job title:</strong> <%= @form.job_title %></p>
<p><strong>Company name:</strong> <%= @form.company %></p>
<p><strong>Comment:</strong> <%= simple_format @form.comment %></p>
<p><strong>Rating:</strong> <%= @form.rating %></p>
<% if @form.would_recommend %>
<p><strong>Recommended</strong></p>
<% end %>
<p><%= link_to "Edit", edit_form_path(@form) %></p>
<p><%= link_to "Delete", form_path(@form), method: :delete, confirm: "Are you sure?" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Questionnaire</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

	<header class="navbar">
		<div class="navbar-inner">
		<%= link_to "Home", forms_path, :class => 'brand' %>
		<ul class="nav">
      <li><%= link_to "All responses", forms_path %></li>
      <li><%= link_to "New response", new_form_path %></li>
    </ul>
	</div>
	</header>
	<div id="main" role="main">
		<div class="container">
			<div class="content">
				<div class="row-fluid">
					<div class="span12">
						<% if flash.any? %>
						<div class="alert"><%= flash[:success] %>
							<a class="close" data-dismiss="alert">&#215;</a>
						</div>
						<% end %>
						<%= yield %>
					</div>
				</div>
				<footer>
				</footer>
			</div>
		</div> <!--! end of .container -->
	</div> <!--! end of #main -->

</body>
</html>